title: Hay Mamaaa!!!!
author: Erick Ramirez
email: erramire@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  ya vamonos para Cuba y para colombia.

# social links
twitter_username: @erramiremsft
github_username:  erramire

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
